# Generated by Django 5.2.7 on 2025-11-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='985857b01fe1f102236e3449044b9d011e44b915', max_length=40, unique=True),
        ),
    ]
