# Generated by Django 5.2.7 on 2025-11-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='edad3d5516f04aada9095704d0dc6c538e20924d', max_length=40, unique=True),
        ),
    ]
