# Generated by Django 5.2.7 on 2025-11-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='d4ccaa22ac62a77fcd667d84c63371b8a0596d1a', max_length=40, unique=True),
        ),
    ]
