# Generated by Django 5.2.7 on 2025-11-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='b21434f931b012ef47fefe7ba7ae9d3b01f7fd30', max_length=40, unique=True),
        ),
    ]
