# Generated by Django 5.2.7 on 2025-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0005_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='0663f387fa0fe3f9847ffd252ffb8f9c952a266f', max_length=40, unique=True),
        ),
    ]
