# Generated by Django 5.2.7 on 2025-11-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='e9b422c3f509ad7bca3b983605f35ce5a249d25d', max_length=40, unique=True),
        ),
    ]
