# Generated by Django 5.2.7 on 2025-11-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0007_alter_userapikey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='3ccb48e5f1222d01f6e42db616f7df4cd42f8097', max_length=40, unique=True),
        ),
    ]
