# Generated by Django 5.2.7 on 2025-11-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_alter_userapikey_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='device',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='65fa03c2b7f1d2dac58a8127461fafb16b127528', max_length=40, unique=True),
        ),
    ]
