# Generated by Django 5.2.7 on 2025-11-07 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0009_remove_sensordata_device_sensordata_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userapikey',
            name='key',
            field=models.CharField(default='1164b6fdce089e4ad9a825d93231a5782473d43b', max_length=40, unique=True),
        ),
    ]
